#!/usr/bin/env python3
"""Fetch Codex plan limits and watch local session token counters.

The networked account query runs outside the renderer through Codex's official
app-server. The renderer only sources small, mode-0600 cache files.
"""

from __future__ import annotations

import argparse
from datetime import datetime
import json
import os
from pathlib import Path
import queue
import shlex
import signal
import subprocess
import threading
import time
from typing import Any

CLIENT_VERSION = "0.1.1"
RPC_TIMEOUT = 15
STOP = False


def atomic_env(path: Path, values: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.{os.getpid()}.tmp")
    lines = ["# Generated by Coralline Codex; contains no credentials."]
    for key in sorted(values):
        value = "" if values[key] is None else str(values[key])
        lines.append(f"{key}={shlex.quote(value)}")
    temporary.write_text("\n".join(lines) + "\n", encoding="utf-8")
    os.chmod(temporary, 0o600)
    os.replace(temporary, path)


def reader(stream, messages: queue.Queue) -> None:
    try:
        for line in stream:
            messages.put(line)
    finally:
        messages.put(None)


def wait_response(messages: queue.Queue, request_id: int, deadline: float) -> dict:
    while time.monotonic() < deadline:
        try:
            line = messages.get(timeout=max(0.01, deadline - time.monotonic()))
        except queue.Empty as exc:
            raise TimeoutError(f"app-server request {request_id} timed out") from exc
        if line is None:
            raise RuntimeError("app-server closed before responding")
        try:
            message = json.loads(line)
        except json.JSONDecodeError:
            continue
        if message.get("id") == request_id:
            if message.get("error"):
                raise RuntimeError("app-server rejected the account usage request")
            result = message.get("result")
            if not isinstance(result, dict):
                raise RuntimeError("app-server returned an invalid account usage response")
            return result
    raise TimeoutError(f"app-server request {request_id} timed out")


def fetch_account(codex_bin: str) -> tuple[dict, dict]:
    process = subprocess.Popen(
        [codex_bin, "app-server", "--stdio"],
        stdin=subprocess.PIPE,
        stdout=subprocess.PIPE,
        stderr=subprocess.DEVNULL,
        text=True,
        encoding="utf-8",
        bufsize=1,
    )
    try:
        if process.stdin is None or process.stdout is None:
            raise RuntimeError("could not open Codex app-server pipes")
        messages: queue.Queue = queue.Queue()
        threading.Thread(target=reader, args=(process.stdout, messages), daemon=True).start()
        deadline = time.monotonic() + RPC_TIMEOUT
        initialize = {
            "method": "initialize",
            "id": 1,
            "params": {
                "clientInfo": {
                    "name": "coralline_codex",
                    "title": "Coralline Codex",
                    "version": CLIENT_VERSION,
                }
            },
        }
        process.stdin.write(json.dumps(initialize, separators=(",", ":")) + "\n")
        process.stdin.flush()
        wait_response(messages, 1, deadline)
        process.stdin.write('{"method":"initialized"}\n')
        process.stdin.write('{"method":"account/rateLimits/read","id":2}\n')
        process.stdin.flush()
        rate_limits = wait_response(messages, 2, deadline)
        process.stdin.write('{"method":"account/usage/read","id":3}\n')
        process.stdin.flush()
        try:
            account_usage = wait_response(messages, 3, deadline)
        except (RuntimeError, TimeoutError):
            account_usage = {}
        return rate_limits, account_usage
    finally:
        if process.stdin and not process.stdin.closed:
            process.stdin.close()
        try:
            process.wait(timeout=1)
        except subprocess.TimeoutExpired:
            process.terminate()
            try:
                process.wait(timeout=1)
            except subprocess.TimeoutExpired:
                process.kill()
                process.wait()


def window_label(minutes: Any, fallback: str) -> str:
    if not isinstance(minutes, (int, float)) or isinstance(minutes, bool):
        return fallback
    choices = ((300, "5h"), (1440, "1d"), (10080, "7d"), (43200, "30d"))
    for expected, label in choices:
        if abs(minutes - expected) / expected <= 0.1:
            return label
    return fallback


def rate_env(rate_result: dict, usage_result: dict) -> dict[str, Any]:
    aggregate = rate_result.get("rateLimits")
    if not isinstance(aggregate, dict):
        aggregate = {}
    values: dict[str, Any] = {
        "CORALLINE_RATE_AVAILABLE": 0,
        "CORALLINE_RATE_UPDATED": int(time.time()),
        "CORALLINE_PLAN": aggregate.get("planType") or "",
    }
    index = 0
    for kind in ("primary", "secondary"):
        window = aggregate.get(kind)
        if not isinstance(window, dict) or window.get("usedPercent") is None:
            continue
        index += 1
        used = max(0, min(100, round(float(window["usedPercent"]))))
        minutes = window.get("windowDurationMins")
        prefix = f"CORALLINE_LIMIT{index}_"
        values.update(
            {
                prefix + "LABEL": window_label(minutes, kind),
                prefix + "USED": used,
                prefix + "REMAINING": 100 - used,
                prefix + "RESET": window.get("resetsAt") or "",
                prefix + "WINDOW_MINS": minutes or "",
            }
        )
    if index:
        values["CORALLINE_RATE_AVAILABLE"] = 1
        values["CORALLINE_LIMIT_COUNT"] = index
    summary = usage_result.get("summary")
    if isinstance(summary, dict):
        values["CORALLINE_LIFETIME_TOKENS"] = summary.get("lifetimeTokens") or ""
    return values


def refresh_rate_cache(codex_bin: str, cache: Path) -> dict[str, Any]:
    rate_result, usage_result = fetch_account(codex_bin)
    values = rate_env(rate_result, usage_result)
    atomic_env(cache, values)
    return values


def token_env(payload: dict) -> dict[str, Any]:
    info = payload.get("info")
    if not isinstance(info, dict):
        return {"CORALLINE_SESSION_AVAILABLE": 0}
    total = info.get("total_token_usage") or info.get("totalTokenUsage")
    last = info.get("last_token_usage") or info.get("lastTokenUsage")
    if not isinstance(total, dict):
        return {"CORALLINE_SESSION_AVAILABLE": 0}

    def value(data: dict, snake: str, camel: str) -> Any:
        result = data.get(snake, data.get(camel, ""))
        return result if isinstance(result, (int, float)) and not isinstance(result, bool) else ""

    last = last if isinstance(last, dict) else {}
    return {
        "CORALLINE_SESSION_AVAILABLE": 1,
        "CORALLINE_SESSION_TOTAL": value(total, "total_tokens", "totalTokens"),
        "CORALLINE_SESSION_INPUT": value(total, "input_tokens", "inputTokens"),
        "CORALLINE_SESSION_CACHED": value(total, "cached_input_tokens", "cachedInputTokens"),
        "CORALLINE_SESSION_OUTPUT": value(total, "output_tokens", "outputTokens"),
        "CORALLINE_CONTEXT_USED": value(last, "total_tokens", "totalTokens"),
        "CORALLINE_CONTEXT_WINDOW": info.get("model_context_window", info.get("modelContextWindow", "")),
    }


def extract_rollout(path: Path) -> dict[str, Any]:
    latest: dict[str, Any] = {"CORALLINE_SESSION_AVAILABLE": 0}
    try:
        with path.open(encoding="utf-8") as handle:
            for line in handle:
                try:
                    event = json.loads(line)
                except json.JSONDecodeError:
                    continue
                payload = event.get("payload")
                if (
                    event.get("type") == "event_msg"
                    and isinstance(payload, dict)
                    and payload.get("type") == "token_count"
                ):
                    latest = token_env(payload)
    except OSError:
        pass
    return latest


def parse_timestamp(value: Any) -> float:
    if not isinstance(value, str):
        return 0
    try:
        return datetime.fromisoformat(value.replace("Z", "+00:00")).timestamp()
    except ValueError:
        return 0


def process_tree(pid: int) -> list[int]:
    """Return a Linux process and its descendants without external commands."""
    pending = [pid]
    seen: set[int] = set()
    while pending:
        current = pending.pop()
        if current in seen or current <= 0:
            continue
        seen.add(current)
        children = Path(f"/proc/{current}/task/{current}/children")
        try:
            pending.extend(int(value) for value in children.read_text().split())
        except (OSError, ValueError):
            pass
    return list(seen)


def rollout_from_pid(pid: int) -> Path | None:
    candidates: set[Path] = set()
    for process_id in process_tree(pid):
        fd_dir = Path(f"/proc/{process_id}/fd")
        if not fd_dir.is_dir():
            continue
        try:
            descriptors = list(fd_dir.iterdir())
        except OSError:
            continue
        for fd in descriptors:
            try:
                target = Path(os.readlink(fd))
            except OSError:
                continue
            if target.name.startswith("rollout-") and target.suffix == ".jsonl" and target.is_file():
                candidates.add(target)
    if not candidates:
        return None
    return max(candidates, key=lambda path: path.stat().st_mtime)


def rollout_meta(path: Path) -> tuple[float, str]:
    try:
        with path.open(encoding="utf-8") as handle:
            first = json.loads(handle.readline())
    except (OSError, json.JSONDecodeError):
        return 0, ""
    if first.get("type") != "session_meta" or not isinstance(first.get("payload"), dict):
        return 0, ""
    return parse_timestamp(first.get("timestamp")), str(first["payload"].get("cwd") or "")


def find_rollout(codex_home: Path, start_epoch: float, cwd: str, pid: int) -> Path | None:
    by_pid = rollout_from_pid(pid)
    if by_pid:
        return by_pid
    sessions = codex_home / "sessions"
    if not sessions.is_dir():
        return None
    candidates: list[tuple[float, Path]] = []
    for path in sessions.rglob("rollout-*.jsonl"):
        try:
            if path.stat().st_mtime < start_epoch - 5:
                continue
        except OSError:
            continue
        created, session_cwd = rollout_meta(path)
        if created >= start_epoch - 5 and session_cwd == cwd:
            candidates.append((created, path))
    if not candidates:
        return None
    candidates.sort(key=lambda item: (abs(item[0] - start_epoch), item[0]))
    return candidates[0][1]


def stop_handler(*_args: Any) -> None:
    global STOP
    STOP = True


def watch(args: argparse.Namespace) -> int:
    signal.signal(signal.SIGTERM, stop_handler)
    signal.signal(signal.SIGINT, stop_handler)
    atomic_env(args.session_cache, {"CORALLINE_SESSION_AVAILABLE": 0})
    last_rate = 0.0
    rollout: Path | None = None
    last_token_values: dict[str, Any] | None = None
    while not STOP:
        now = time.monotonic()
        if now - last_rate >= args.interval:
            try:
                refresh_rate_cache(args.codex_bin, args.rate_cache)
            except Exception:
                pass
            last_rate = now
        if rollout is None or not rollout.exists():
            rollout = find_rollout(args.codex_home, args.start_epoch, args.cwd, args.pid)
        if rollout is not None:
            values = extract_rollout(rollout)
            if values != last_token_values:
                atomic_env(args.session_cache, values)
                last_token_values = values
        time.sleep(1)
    return 0


def format_tokens(value: Any) -> str:
    try:
        number = int(value)
    except (TypeError, ValueError):
        return "?"
    if number >= 1_000_000:
        return f"{number / 1_000_000:.1f}M"
    if number >= 1_000:
        return f"{number / 1_000:.1f}k"
    return str(number)


def status(codex_bin: str, cache: Path) -> int:
    values = refresh_rate_cache(codex_bin, cache)
    plan = values.get("CORALLINE_PLAN") or "unknown"
    print(f"Plan: {plan}")
    count = int(values.get("CORALLINE_LIMIT_COUNT") or 0)
    for index in range(1, count + 1):
        prefix = f"CORALLINE_LIMIT{index}_"
        reset = values.get(prefix + "RESET")
        reset_text = ""
        if reset:
            reset_text = datetime.fromtimestamp(int(reset)).astimezone().strftime("%Y-%m-%d %H:%M %Z")
        print(
            f"{values[prefix + 'LABEL']}: {values[prefix + 'REMAINING']}% remaining"
            + (f"; resets {reset_text}" if reset_text else "")
        )
    lifetime = values.get("CORALLINE_LIFETIME_TOKENS")
    if lifetime:
        print(f"Account token activity: {format_tokens(lifetime)} lifetime")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    sub = parser.add_subparsers(dest="command", required=True)
    fetch = sub.add_parser("fetch")
    fetch.add_argument("--codex-bin", required=True)
    fetch.add_argument("--rate-cache", required=True, type=Path)
    show = sub.add_parser("status")
    show.add_argument("--codex-bin", required=True)
    show.add_argument("--rate-cache", required=True, type=Path)
    extract = sub.add_parser("extract")
    extract.add_argument("--rollout", required=True, type=Path)
    extract.add_argument("--session-cache", required=True, type=Path)
    watcher = sub.add_parser("watch")
    watcher.add_argument("--codex-bin", required=True)
    watcher.add_argument("--codex-home", required=True, type=Path)
    watcher.add_argument("--rate-cache", required=True, type=Path)
    watcher.add_argument("--session-cache", required=True, type=Path)
    watcher.add_argument("--start-epoch", required=True, type=float)
    watcher.add_argument("--cwd", required=True)
    watcher.add_argument("--pid", required=True, type=int)
    watcher.add_argument("--interval", type=int, default=60)
    args = parser.parse_args()
    if args.command == "fetch":
        refresh_rate_cache(args.codex_bin, args.rate_cache)
        return 0
    if args.command == "status":
        return status(args.codex_bin, args.rate_cache)
    if args.command == "extract":
        atomic_env(args.session_cache, extract_rollout(args.rollout))
        return 0
    return watch(args)


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as error:
        print(f"coralline-codex usage: {error}", file=os.sys.stderr)
        raise SystemExit(1)
